name: Update README
on:
  push:
    branches: [lulubasheer728-patch-1]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update README
        run: |
          current_date=$(date +"%B %d, %Y")
          sed -i "s/Last Updated: .*/Last Updated: $current_date/" README.md

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "Update README last updated timestamp" || echo "No changes to commit"
            git push origin HEAD

      - name: List Files
        run: ls -la